name: hello

on: 
- push

jobs:
  echo:
  
    runs-on: ubuntu-latest
    
    steps:
    - id: one
      uses: actions/checkout@v2
      
    - name: from docker
      uses: docker://hello-world:latest  
      
    - id: two
      run: echo hello
      
    - id: three
      run: |
        echo Greeting
        echo good morning
