name: hello

on: 
- push

jobs:
  echo:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: check out repository
      uses: actions/checkout@v2
      
    - name: say hello
      run: echo hello
      
    - name: multiline script
      run: |
        echo Greeting
        echo good morning
